---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(lubridate)
tuesdata <- tidytuesdayR::tt_load('2023-02-07')
tuesdata$big_tech_stock_prices %>% glimpse
```



```{r}
### Creating Tables
stock_prices <- tuesdata$big_tech_stock_prices
companies <- tuesdata$big_tech_companies
stock_prices %>% glimpse()
```

```{r Trading Volume}
fouryears <- lubridate::make_date(seq(year(min(stock_prices$date)),
  year(max(stock_prices$date)),
  by = 4
), 1, 1)

stock_prices %>%
  filter(stock_symbol == "AAPL") %>%
  select(date, volume) %>%
  ggplot(aes(x = date, y = volume)) +
  geom_line() +
  scale_x_date(NULL,
               breaks = fouryears, date_labels = "%Y"
  ) +
  ylab(NULL) +
  scale_y_continuous(labels = label_comma()) +
  labs(title = "Daily Trading Volume")
  
```

```{r 5 Highest Volume}
stock_prices %>%
  filter(stock_symbol == "AAPL") %>%
  select(volume,date) %>%
  top_n(volume, n= 5) %>%
  mutate(date = fct_reorder(as.factor(date), -volume)) %>%
  ggplot(aes(x = date, y = volume, fill = volume)) +
  geom_col() +
  scale_y_continuous(labels = label_comma()) +
  xlab(NULL) +
  ylab(NULL) +
  theme(legend.position = "none", 
        axis.text.y = element_text(color = "grey20", size = 12),
        axis.text.x = element_text(color = "grey20", size = 12)) +
  labs(title = "Highest Volume Days")

```

```{r 5 Best Days}
stock_prices %>%
  filter(stock_symbol == "AAPL") %>%
  select(adj_close, open,date) %>%
  mutate(per_change = ((adj_close - open)/open)) %>%
  select(date, per_change) %>%
  top_n(per_change, n= 5) %>%
  mutate(date = fct_reorder(as.factor(date), -per_change)) %>%
  ggplot(aes(x = date, y = per_change, fill = per_change)) +
  geom_col() + 
  scale_y_continuous(labels = scales::percent) +
  xlab(NULL) +
  ylab(NULL) +
  theme(legend.position = "none", 
        axis.text.y = element_text(color = "grey20", size = 12),
        axis.text.x = element_text(color = "grey20", size = 12)) +
  labs(title = "Largest Positive Days", 
       subtitle = "Percent Difference between open and closing price")

```

```{r}
stock_prices %>%
  filter(stock_symbol == "AAPL") %>%
  select(date, adj_close) %>%
  ggplot(aes(x = date, y = adj_close)) +
  geom_line() +
  ylab(NULL) +
  scale_x_date(NULL,
               breaks = fouryears, date_labels = "%Y"
  ) +
  scale_y_continuous(labels = label_comma()) +
  labs(title = "Daily Stock Price")

```

